# Generated by Django 4.2.15 on 2025-10-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_vendedores_password_vendedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='reseñaBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('blogComentado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
            ],
            options={
                'verbose_name': 'Reseña blogs',
                'verbose_name_plural': 'Reseña blogs',
            },
        ),
    ]
