# Generated by Django 4.2.15 on 2025-10-30 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_vendedores_password_vendedor'),
        ('reseñas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reseñablog',
            options={'verbose_name': 'Reseña del blog', 'verbose_name_plural': 'Reseñas de blogs'},
        ),
        migrations.RenameField(
            model_name='reseñablog',
            old_name='nombreUsuario',
            new_name='nombre_usuario',
        ),
        migrations.RemoveField(
            model_name='reseñablog',
            name='blogComentado',
        ),
        migrations.AddField(
            model_name='reseñablog',
            name='blog_comentado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='blog.blogs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reseñablog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
