# Generated by Django 4.2.15 on 2025-10-30 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_vendedores_password_vendedor'),
        ('reseñas', '0002_alter_reseñablog_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseñaTienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('calificacion', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas_tienda', to='blog.formuser')),
            ],
            options={
                'verbose_name': 'Reseña de la tienda',
                'verbose_name_plural': 'Reseñas de la tienda',
            },
        ),
    ]
