# Generated by Django 4.2.15 on 2025-10-30 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reseñas', '0003_reseñatienda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reseñatienda',
            old_name='calificacion',
            new_name='calificacion_tienda',
        ),
        migrations.RenameField(
            model_name='reseñatienda',
            old_name='comentario',
            new_name='comentario_tienda',
        ),
    ]
