# Generated by Django 4.2.15 on 2025-10-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='password_vendedor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
