# Generated by Django 5.2.6 on 2025-10-04 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
