# Generated by Django 4.2.15 on 2025-11-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_vendedores_password_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
