# Generated by Django 5.2.6 on 2025-10-05 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogs_categoria_delete_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
