# Generated by Django 5.2.6 on 2025-10-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_disponible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='contenido',
        ),
        migrations.AddField(
            model_name='blogs',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
