# Generated by Django 4.2.15 on 2025-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogs_detalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedores',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
