# Generated by Django 4.2.15 on 2025-12-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_vendedores_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedores',
            name='estado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
