# Generated by Django 5.2.6 on 2025-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blogs_contenido_blogs_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
