# Generated by Django 5.2.6 on 2025-10-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_formuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
