# Generated by Django 5.2.6 on 2025-10-17 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogs_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='formuser',
            options={'verbose_name': 'Usuarios', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogs')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.formuser')),
            ],
            options={
                'verbose_name': 'Ventas',
                'verbose_name_plural': 'Ventas',
            },
        ),
    ]
