# Generated by Django 4.2.15 on 2025-10-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PanelAdminAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_admin', models.CharField(max_length=200)),
                ('correo_admin', models.CharField(max_length=200)),
                ('password_admin', models.CharField(max_length=200)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
