# Generated by Django 4.2.15 on 2025-10-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administradores', '0001_initial'),
    ]

    operations = [
    ]
